version: "3.4"
services:
  controller:
    build:
      context: ./deployer
    restart: unless-stopped
    env_file:
      - .controller.env
    environment:
      - "CUID=${CUID}"
      - "CGID=${CGID}"
    ports:
      - 3456:3000
    networks:
      - controller-network
    privileged: true
    volumes:
      - controller_base:/controller
      - ./controller/scripts/cron.d:/etc/cron.d
      - "$DOCKER_BIN:/usr/bin/docker"
      - /var/run/docker.sock:/var/run/docker.sock

  nginx:
    image: nginx
    restart: unless-stopped
    env_file:
      - .controller.env
    ports:
      - 8900:80
    networks:
      - controller-network
    volumes:
      - controller_base:/controller
      - "$PWD/images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"

  rauthy:
    image: quay.io/krakaw/rauthy:latest
    restart: unless-stopped
    environment:
      - LISTEN=0.0.0.0:3031
      - BASIC_AUTH_MESSAGE="Rauthy says no"
      - AUTH_FILE=/root/config/auth.json
    volumes:
      - rauthy_config:/root/config
    networks:
      - controller-network
    ports:
      - 3032:3031
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3031/status" ]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  controller-network:

volumes:
  rauthy_config:
  controller_base:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
