version: "3.4"
services:
  {TEMPLATES}
  logs:
    restart: unless-stopped
    image: "mthenw/frontail"
    volumes:
      - "$HOST_RELEASE_PATH/$API_BRANCH_URL/logs:/logs"
    networks:
      - controller-network
      - internal-network
    command:
      - --url-path=/logs
      - --number=1000
      - /logs/*
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:9001/logs"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  sockets:
    restart: unless-stopped
    image: krakaw/sockets:latest
    user: "${CUID}:${CGID}"
    volumes:
      - "$HOST_RELEASE_PATH/$API_BRANCH_URL/socks:/socks"
    networks:
      - internal-network
    command: >
      bash -c "/usr/bin/socat-to-tcp.sh /socks/api.sock api 3001 && /usr/bin/socat-to-tcp.sh /socks/ysg.sock api 9081 && /usr/bin/socat-to-tcp.sh /socks/logs.sock logs 9001 && sleep 3 && chmod 666 /socks/* && tail -f /dev/null"

networks:
  controller-network:
    external: true
  internal-network:
    internal: true

volumes:
  storage:
