#!/bin/bash

TEMPLATE_FILE=$1
OUTPUT_FILE=$2

TEMPLATE_STRINGS=""
for TEMPLATE in ./docker-services.d/*.yml; do
  TEMPLATE_STRING=$(tr <"$TEMPLATE" '\n' '§')
  TEMPLATE_STRINGS="$TEMPLATE_STRINGS§$TEMPLATE_STRING"
done

sed "s|{TEMPLATES}|$TEMPLATE_STRINGS|" "$TEMPLATE_FILE" | tr '§' '\n' >"$OUTPUT_FILE"
